# Generated by Django 5.2.7 on 2025-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_created_at_product_discount_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='user123', max_length=128),
            preserve_default=False,
        ),
    ]
