# Generated by Django 5.2.7 on 2025-11-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
