# Generated by Django 5.2.7 on 2025-11-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
